### ISSUE TITLE
部分数据表的初始数据updated_at字段为空，项目初始化失败

### ISSUE THREAD

**Issue by pyronn** [ch3nnn/webstack-go#25]
在`table_category`和`table_site`发现部分数据updated_at设置`NULL`, 数据库限制该字段不允许为`NULL`，初始化项目失败

**Comment by ch3nnn** [comment]
感谢你的反馈,  稍后会完善初始化数据

**Comment by ch3nnn** [comment]
已提交  https://github.com/ch3nnn/webstack-go/pull/26

**Comment by pyronn** [comment]
可以了，多谢
