### ISSUE TITLE
扩展功能建议

### ISSUE THREAD

**Issue by jihanlingyu** [ch3nnn/webstack-go#30]
不够用，建议扩展出一个站点主题。
在分类的基础上再加一层，（站点主题）    比如这个站点主题可以有  AI相关，财经相关，IT相关。 可切换站点达到更好的效果。不用额外建站，望采纳

**Comment by jihanlingyu** [comment]
分类标签解决不了问题，会导致同一界面网址过多。
相当于子站，比如我一个子站专注ai，一个子站专注前端，一个子站专注后端，一个子站专注摄影

**Comment by jihanlingyu** [comment]
啊觉得麻烦就算了，我只是觉得这样体验好一点，分享给不同行业的人也是可以直接给不同的url或者站点

**Comment by ch3nnn** [comment]
我大概理解你的需求, 可能类似 https://nav.cmsblogs.cn/ 分类中的财经频道, AI应用。
