### ISSUE TITLE
网站logo建议缓存在服务端

### ISSUE THREAD

**Issue by JackMaBaLaBaLa** [ch3nnn/webstack-go#32]
对于自动获取的logo，每次打开导航站会访问logo所在网站获取。如果网络环境差的情况，会花不少时间去获取logo，并且可能出现获取不到logo的情况，影响到导航站的展示，拖累性能。
建议获取一次logo后，可以保存在服务端，从服务端拉取logo。

**Comment by ch3nnn** [comment]
已新增。先从静态资源实现   https://github.com/ch3nnn/webstack-go/pull/34

**Comment by JackMaBaLaBaLa** [comment]
> 已新增。先从静态资源实现 #34
发现了一个小问题。就是对于自动获取成功的网站logo是缓存在服务端了。对于有些自动获取logo失败，手动填写logo图片地址的情况，并没有缓存在服务端。
