### ISSUE TITLE
一些css资源来自于cdn，内网部署无法访问外网cdn，则无法打开管理面板

### ISSUE THREAD

**Issue by 0cara0** [ch3nnn/webstack-go#41]
是否可处理，谢谢。
**如下图**：
![11111](https://github.com/ch3nnn/webstack-go/assets/14905941/eb5bf5c6-c882-4371-b05a-0cbf7eb897c1)

**Comment by ch3nnn** [comment]
感谢反馈,  暂时没有打算做这快处理,  这边可以自行在每个 html head 标签里面修改, 并将相关静态资源放到 assets/bootstrap/ 文件里

**Comment by 0cara0** [comment]
谢谢

**Comment by ch3nnn** [comment]
已修复 https://github.com/ch3nnn/webstack-go/releases/tag/v2.1.0
