### ISSUE TITLE
docker-compose -f docker-compose.yml up -d执行报错

### ISSUE THREAD

**Issue by ontopzzj** [ch3nnn/webstack-go#53]
[root@localhost /data/webapp/webstack-go ]$docker-compose -f docker-compose.yml up -d
[+] Building 4.7s (1/1) FINISHED                                                                                                                                     
 => ERROR [webstack-go-service internal] booting buildkit                                                                                                       4.7s
 => => pulling image moby/buildkit:buildx-stable-1                                                                                                              4.6s
 => => creating container buildx_buildkit_default                                                                                                               0.0s
------
 > [webstack-go-service internal] booting buildkit:
------
Error response from daemon: No such image: moby/buildkit:buildx-stable-1

**Comment by ch3nnn** [comment]
感谢关注。 错误提示没有 moby/buildkit:buildx-stable-1 镜像,  确定是项目中 docker-compose.yml 文件嘛。出现此类错误的原因是版本不兼容。升级 Docker 版本或者选择其他版本。

**Comment by ontopzzj** [comment]
确实是docker版本问题，感谢大佬抽空回复
