### ISSUE TITLE
安装中端口占用问题

### ISSUE THREAD

**Issue by leanovv** [ch3nnn/webstack-go#54]
如题，我安装mysql与redis之后，3306与6379都被使用了，这个时候我应该暂停服务，还是应该修改docker-compose.yml文件换成其他端口，我尝试暂停服务，然后使用默认端口，但是都会提示“错误码：10114 错误信息：Redis 连接失败”。

**Comment by ch3nnn** [comment]
`docker-compose.yml`文件中的`mysq`与`redis` 中的映射端口换成其他的, 然后执行`docker-compose -f docker-compose.yml down`  删除容器后, 重新执行`docker-compose -f docker-compose.yml up -d `

**Comment by leanovv** [comment]
配置了docker-compose.yml里面的mysql数据库密码，初始化的时候可以连上，但是重启后就失败，测试了发现只能用默认123456作为密码，其他的都不行

**Comment by ch3nnn** [comment]
> 配置了docker-compose.yml里面的mysql数据库密码，初始化的时候可以连上，但是重启后就失败，测试了发现只能用默认123456作为密码，其他的都不行

 如果是修改密码可以查看 #49
