### ISSUE TITLE
支持页面登录才可以查看吗

### ISSUE THREAD

**Issue by joe5chen** [ch3nnn/webstack-go#56]
支持页面登录才可以查看吗，我想部署一些私人的类型

**Comment by ch3nnn** [comment]
感谢关注, 没太理解你这边意思

**Comment by joe5chen** [comment]
web页面默认就可以打开嘛，支持登录才能查看吗？

**Comment by ch3nnn** [comment]
你是指的 http://hao.ch3nnn.cn/ 地址吗

**Comment by joe5chen** [comment]
是的

**Comment by ch3nnn** [comment]
这个是我个人导航地址.  你可以按照文档 `docker-compose` 部署个人的服务

**Comment by joe5chen** [comment]
我部署个人服务后，发现不需要登录也能看到主页。项目支持登录后才能查看页面吗

**Comment by ch3nnn** [comment]
我大概理解你这边意思了, 暂不支持. 首页默认是无权限的, 你可以 fork 项目自行修改.

**Comment by joe5chen** [comment]
好的谢谢
