### ISSUE TITLE
docker部署报错

### ISSUE THREAD

**Issue by ccHR0305** [ch3nnn/webstack-go#64]
docker部署成功，运行一段时间后：
1. mysql意外关闭 ：Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.2.0).

2. 重启mysql后webstack-go-service报错：/go/src/github.com/ch3nnn/webstack-go/internal/repository/mysql/query/site.gen.go:403 Error 1049 (42000): Unknown database 'webstack-go'

3. 重启webstack-go-service后报错:/go/src/github.com/ch3nnn/webstack-go/internal/repository/mysql/mysql.go:98
[error] failed to initialize database, got error Error 1049 (42000): Unknown database 'webstack-go'

**Comment by ccHR0305** [comment]
补充：在arm64机器上部署，所以修改了mysql和redis版本以支持arm架构

**Comment by ch3nnn** [comment]
感谢关注,  因为我没有 arm 机器所以也不好确实是不是数据库兼容问题。 从第一条错误信息感觉是 mysql 挂了导致第二三条错误数据库不存在了, 看看数据库是否还存在 'webstack-go' 这个库。

**Comment by ccHR0305** [comment]
感谢大佬，经排查发现似乎是数据库命名为"webstack-go"的问题。在mysql容器中未发现 'webstack-go' 这个库，手动执行CREATE DATABASE webstack-go; 会报错，不允许库名包含'-'，将数据库名改为webstack重新部署后暂时正常。

补充：我是小白，几乎没有接触过数据库和go语言，如果issue有误还请指正。
