### ISSUE TITLE
是否可以修改默认搜索引擎

### ISSUE THREAD

**Issue by Tingday** [ch3nnn/webstack-go#69]
习惯了在搜狗和谷歌搜索，能不能设置网站搜索引擎自行设置，或者具有客户端cookie保持功能。

**Comment by ch3nnn** [comment]
修改 [        "data": [{"name": "百度", "img": "url(https://www.baidu.com/favicon.ico)", "url": "https://www.baidu.com/s?wd="}]](https://github.com/ch3nnn/webstack-go/blob/master/assets/templates/index/index.html#L29)

对于搜索 url 可以替换下面
- 搜狗  url: "https://www.sogou.com/web?query="
- 谷歌  url: "https://www.google.com/search?q="

对应的 img url 需要获取搜索引擎的

**Comment by Tingday** [comment]
改了还是不行。而且我看到你代码有想实现保存功能，但是不完整。

**Comment by ch3nnn** [comment]
> 改了还是不行。但是我看到你的代码有想实现保存功能，不完整。[ var localSearchData = localStorage.getItem("searchData"); if (localSearchData && (searchData.custom === localSearchData.custom)) { searchData = JSON.parse(localSearchData) }](https://github.com/ch3nnn/webstack-go/blob/master/assets/bootstrap/js/index/header.js#L87)

很抱歉回复这么晚,  大体看了下如果要实现自定义搜索可以修改此处  [script userDefinedSearchData](https://github.com/ch3nnn/webstack-go/blob/master/assets/templates/index/index.html#L24 ) 。对于实现客户端cookie保持功能可能暂时无法实现

复制下面代码
```js
<script>
    var userDefinedSearchData = {
        "custom": true,
        "thisSearch": "https://www.google.com/search?q=",
        "thisSearchIcon": "url(https://www.google.com/favicon.ico)",
        "hotStatus": true,
        "data": [
            {"name": "谷歌", "img": "url(https://www.google.com/favicon.ico)", "url": "https://www.google.com/search?q="},
            {"name": "搜狗", "img": "url(https://www.sogou.com/favicon.ico)", "url": "https://www.sogou.com/web?query="},
        ]
    };
</script>
```

userDefinedSearchData  自定义搜索引擎
- custom: 是否启用自定义配置
- thisSearch: 当前搜索引擎的搜索链接
- thisSearchIcon: 当前搜索引擎的图标链接，格式为url(图片链接)
- hotStatus: 是否启用搜热词功能
- data: 多搜索引擎配置
