### ISSUE TITLE
疑似项目在数据库连接方面，没有完全设计好

### ISSUE THREAD

**Issue by 8MiYile** [ch3nnn/webstack-go#82]
是这样的 我在打开的时候 我根据教程 在网页执行安装
但在MySQL这块 我使用了自定义用户名
提示安装完毕了 但是在重新打开的时候 却提示
![image](https://github.com/ch3nnn/webstack-go/assets/25455400/038362c3-bfc4-4cb4-9a8f-5472a50783b1)
就很疑惑
版本项目是最新的Release版本 也就是那个 v1.1.0

**Comment by ch3nnn** [comment]
是安装页面输入数据库相关正常提示成功, 然后服务重启提示数据库连接错误?

**Comment by 8MiYile** [comment]
对的 要不然我也不至于重启啊

**Comment by ch3nnn** [comment]
> 对的 要不然我也不至于重启啊 而且我还检查了一下是不是生成的 fat_configs.toml 是不是有问题 结果看了一下，就是和我在网页内设置的一样 所以我就没搞懂为什么会这样

好的 近期我排查一下

**Comment by 8MiYile** [comment]
辛苦了
@ch3nnn

**Comment by ch3nnn** [comment]
已修复 [v1.1.1](https://github.com/ch3nnn/webstack-go/releases/tag/v1.1.1)
